### ISSUE TITLE
Likely oncogenic annotation

### ISSUE THREAD

**Issue by patidarr** [oncokb/oncokb#1639]
How do you annotate a variant as "likely oncogenic" when its not present in allAnnotatedVariants  file I downloaded from the website. 

for example I see the variant SMARCA4:p.G1232D in the file and its a hotspot, but I have a sample on local cBIO with SMARCA4:p.G1232S, which is annotated as likely oncogenic, it it based on hotspot kid of rule? any mutation on the codon G1232 in SMARCA4 will be likely oncogenic? if this is the case I guess there will be a oncogene file you use? what happens to genes like TP53/NOTCH. 

Thanks,
@patidarr

**Comment by jjgao** [comment]
Hi @patidarr, since G1232D was curated as likely oncogenic, we automatically annotate other missense mutations on G1232 as likely oncogenic (unless there is evidence against it).

For hotspot mutations, if not mutations are curated on the position (which is not true in this case), we will annotate it as predicted oncogenic.

**Comment by patidarr** [comment]
Thanks @jjgao, could you please confirm if you do it for all the genes or Oncogenes only?

another question: how do I find if there is evidence against it?

**Comment by zhx828** [comment]
@patidarr we can confirm this rule applies to all genes.
When the allele is particularly annotated as Likely Neutral, the Oncogenic/Likely Oncogenic from other alleles in the same position will not applied.
