### ISSUE TITLE
Enable Admins to list different users

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#1882]
Currently in the user page, we are listing all users. Instead, we could have three buttons `All Users`, `All Registered Users`, `All Commercial Users`, also add a calendar icon to filter the result.

- [ ] Create methods in UserRepository to query two additional categories(corresponding to the two scripts I gave to you)
- [ ] Create methods in UserService to expose these two methods you created above
- [ ] Create APIs, probably makes sense to include a `@RequestParam type` in the `@GetMapping("/users")`
- [ ] Modify the UserManagementPage to include the features

**Comment by victoria34** [comment]
Finished the "All registered users" API and I will improve this feature. Initially, I put User Details as a tab in the User Management page, but I feel it's dangerous since we put User Authority and User Details together, which is easy to cause that admin user may accidentally click the approve button. Therefore, I built a separate page for user details.
