### ISSUE TITLE
Clinical Trial Matching Pipeline error

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2253]
There were two runs last night, one resulted in Error, one completed. Here is the error log from the one failed.

```
Step 1/5: Get all trials...
The number of total trails is: 14722
50/14722
100/14722
150/14722
200/14722
250/14722
300/14722
350/14722
400/14722
450/14722
500/14722
550/14722
600/14722
650/14722
700/14722
750/14722
800/14722
850/14722
900/14722
950/14722
1000/14722
1050/14722
1100/14722
1150/14722
1200/14722
1250/14722
1300/14722
1350/14722
1400/14722
Traceback (most recent call last):
  File "/code/scripts/main.py", line 197, in <module>
    allTrials = getTrials()
  File "/code/scripts/main.py", line 50, in getTrials
    result = getData(url)
  File "/code/scripts/main.py", line 23, in getData
    return response.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Leowisd** [comment]
I tried a lot times and found the reason should be the Server Internet Problem. I run the pipeline multiple times and found if occurred such error, the type of response was 500. So when our script tried to parse that response data as JSON, it would occur such error because the response data was not JSON. 
There was also a similar error occurs: `json.decoder.JSONDecodeError: Expecting value: line 1 column xxxxx (char xxxx)`, which is also because Internet Connection. During reading JSON data the internet connect broke, then there were some JSON format errors in response data made decode error happen.
A potential improvement way is changing trials size during each API call to clinicalTrials.gov.

**Comment by zhx828** [comment]
TODO list:

- [ ] handle 500 from cancer.gov, split 50 trials call to two 25 when it fails

- [ ] Continue the rest of api calls when one failed
