### ISSUE TITLE
Update user details page to use server side pagination

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2342]
The current workflow disadvantages:
- We pull all users to the frontend which takes a lot of time and resource
- We currently use a constant THRESHOLD_NUM_OF_USER to determine the number of users to pull from API. The api supports the pagination.

TODO list:
- [ ] We use React Table as our base table and the library supports the server side pagination by default. Check out https://github.com/tannerlinsley/react-table/tree/v6#server-side-data
- [ ] In the user details page, we want to change the table settings to use the pagination.
- [ ] Update the endpoint to support pagination
- [ ] Update the swagger codegen to update the api client (the team can help with this)
- [ ] (Optional) Support server side sorting

**Comment by calvinlu3** [comment]
If we implement pagination, we would also need to incorporate ElasticSearch into the project to support the searching functionality. There has been a lot of updates to ES since jhipster 6.10.3 (current project version), so we should wait until we upgrade our project to jhipster v7.x.

Instead, we want to figure out if we can cache the find all user method.
