### ISSUE TITLE
Two-tiered Article Presentation View

### ISSUE THREAD

**Issue by lukeczapla** [oncokb/oncokb#2714]
For the Article pipeline:

1) Frontend view should include a "Most Relevant" group and a "Possibly Relevant" group for every match.
2) The system should partition the matches so that:
a) Very good matches with multiple hits within the full-text (and not in the references/citations) are promoted to Most Relevant
b) Anything at all that is found with a match in either the abstract or the full-text PDF is included in "Possibly Relevant", so that no information at all is lost in the process.  This tier would have to be more extensive, ignoring limits.
c) There are suitable article limits for the "Most Relevant" group so that it is a reasonable amount of articles (for example, 5 articles maximum) for curators to look over.
3) Spreadsheet view should be simplified to present these with the correct labels.
4) Tier 2 (Possibly Relevant) should also include matches to both the main text and any supporting documents that are involved, when available, and have the same presentation options through the frontend.

**Comment by zhx828** [comment]
Here are the issues we found and need to address
- [ ] AKT1-A399T-24809327: the score is -2, but article mentions about the gene/alteration though. How is the -2 calculated? Seems like a valid paper
- [ ] AKT1-E91D-21138868: this article has a very high score, but the alteration is related to PTEN, not AKT1
- [ ] AKT1-E94K-25952756: this is related to VHL E94K, not ARK.
- [ ] AKT1-E94K-28931550: why is this related at all? This article again has been mapped to too many alterations since it has a table.
- [ ] AKT1-F161L-26338797: this is related to RAB35 F161L, not ARK.
I just realize that if we could list all criteria on the page, that would be super useful. Is it difficult to do?

**Comment by zhx828** [comment]
@lukeczapla could you look into the ` AKT1-E91D-21138868` above?

**Comment by lukeczapla** [comment]
I can't, because it looks like it zapped it away with that test
<img width="1437" alt="Screen Shot 2021-11-15 at 10 59 52 AM" src="https://user-images.githubusercontent.com/15238658/141813641-530258e2-808b-44f6-ba76-1d03d8698bd1.png">

**Comment by lukeczapla** [comment]
I see it on the AIML server though, this is odd... let me see what's going on

**Comment by lukeczapla** [comment]
okay, I found the issue - PTEN wasn't in the gene list I used (from our old GeneMaps back when annotating every abstract), so I copied over the one from another file, it should be gone now because I ran that test by hand and got "Skipping article 21138868, seems to be another gene (validateText())"

**Comment by lukeczapla** [comment]
annotating full-text and abstracts will have to wait until the MongoDB is on the local host again to bombard it with all the data quickly (that on-prem Mongo falls apart with this approach) so I think GeneMaps was a terrible place to get the gene names from but now with this simple list that was used everywhere else it's easy and I added some really common synonyms like p53 and p21 at the beginning of that too, because they were ideal search criteria.
