### ISSUE TITLE
Article Pipeline - Revisions / Bug-fix for Point System, Abstract-only results

### ISSUE THREAD

**Issue by lukeczapla** [oncokb/oncokb#2794]
- [x] Place abstract data in Analysis tab for articles that do not have any full text but appear in results for variant curation

- [x] Check points for mentions of alteration in the abstract

- [x] Debug points system (B, C, E, F) to assign correct points for articles with alteration and gene name in the titles

- [x] Assign more data for items in all annotated variants (AAVariants key) after checks are finished

- [x] Also investigate PMID 24933606 - wrong PDF (a license file shows up) and points should be assigned for the information in the Pubmed records.  And investigate missing Solr articles (increase id key length or append last two PMID digits for each to avoid collisions)

**Comment by zhx828** [comment]
- [ ] Investigate PMID 27197157 for AKT1 - K111N. The K111N is associated with the gene PIK3CA. I thought we fixed this. Maybe because of the `-` in between?
- [ ] Investigate PMID 16474404, we have full pdf, but it's not associated with BRAF/A246P. But it should be. It should also be associated with BRAF/Q257R
- [ ] PMID 26996308 shows open access from Cell. Is it possible to index it?
- [ ] PMID 32429639 has an English abstract, but main text is in Chinese. Can we exclude such articles?

**Comment by lukeczapla** [comment]
PMID 24933606 - we don't have the license unfortunately, so upon visiting the page it only finds this PDF document, I will have to see if I can blacklist the filename or something.

**Comment by lukeczapla** [comment]
PMID 16474404 appears now for both BRAF A246P and Q257R, and 27197157 has been dropped from AKT1 K111N and the log noted it was for PIK3CA

**Comment by lukeczapla** [comment]
so I will have to investigate blacklisting t
