### ISSUE TITLE
Show gene genome coordinates on both gene/alteration pages

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2808]
This is a part of FDA recognition that we need to show the coordinates especially for the range mutations. For example, Deletion, Truncating Mutations and Oncogenic Mutations.

**Comment by calvinlu3** [comment]
From weekly meeting:

- Remove the text `Oncogenic Mutations includes all variants annotated as oncogenic and likely oncogenic.` from the gene summary
![image](https://user-images.githubusercontent.com/59149377/146990792-c1fa4e32-20bb-40ac-908b-6e3aed2ebd3c.png)

- Move the checkbox, y axis slider, download, legend to the bottom of the lollipop plot. The reason is because the table moves when you hover and causes a flicker. The checkbox is easy to move, but the other three items are from cbioportal react-mutation-mapper library and not sure if we can adjust the positions.
![image](https://user-images.githubusercontent.com/59149377/146991140-477a00a6-fe45-478f-8ab7-c646e62e65b3.png)

- Update the categoricalAlterationDescription text for oncogenic mutations
    - Include the gene name and genomic coordinates
    - Also move the text to the right of the gene name
    - 
![image](https://user-images.githubusercontent.com/59149377/146991910-04943d73-696b-4350-b7e2-112b2d33a734.png)
