### ISSUE TITLE
Examine whether 19200582 is no longer associated 

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2860]
The article should be associated with BRAF	A598V

**Comment by zhx828** [comment]
https://www.sciencedirect.com/science/article/abs/pii/S0046817708005455?via%3Dihub

**Comment by lukeczapla** [comment]
It is back, it might've had to do with this whitespace parser so I just turned it on when alteration has a * for deletion (like E17*) because the other parser dropped special characters and then it took forever by including tons of wrong ones and mightve missed some because the * was thrown away from the input and then whatever top 500 -> top 300 came up could've missed one of the real answers and just caused it to take forever dropped every PMID with manual checks from scoring..
