### ISSUE TITLE
Identity whether alteration is mentioned in the article table

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2862]
For some articles with only one alteration match, if the alteration is mentioned in the table, it's highly likely a mismatch. If we could identify the matter, maybe giving it a low score(1).

**Comment by lukeczapla** [comment]
I have a plan for this one now having done the sentences and this SentenceDetectorME tool from OpenNLP

1) Pull "sentence" using rules that work well for text in the regular setting of a section.
2) Put through sentence detector and use low probability as a metric.  Counting numeric quantities helps too but I believe this should work alone.

So one of the tools it seems NLMatics (and possibly Cambridge Scientific/CSI) works with is this (non-free) product with Java API: https://pspdfkit.com/api/java/reference/com/pspdfkit/api/basic/package-summary.html
It really doesn't have direct text extraction and works with the PDFs as-is, but someone in AIML group is installing the endpoints for it, etc., sometimes it helps to pay close attention because these things get discussed briefly so I at least picked up this bit of software tool.

**Comment by zhx828** [comment]
Example: 26498038 BRAF V596V

**Comment by zhx828** [comment]
Luke has an algorithm to identify the table, but need more tests.
