### ISSUE TITLE
Highlight keywords in PDF

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2886]
We want to explore whether we can highlight all keywords(functional/alteration) in the PDF. Even better, if we could highlight in different colors like PubTator does. https://www.ncbi.nlm.nih.gov/research/pubtator/?view=docsum&query=PMC6080616

@lukeczapla I'm curious how the pubtator can show the article in a such nice way?

**Comment by lukeczapla** [comment]
Well, one thing that is helpful is that PMC has HTML views of articles, so could be one way to enhance the quality - rather than ripping the PDFs into a plain text and XHTML version like I do now, to import the HTML directly - it only works with PubmedCentral though but Pubtator could be a good source for HTML versions (I have an HTMLEntry field now but it's coming out of Tika parser which can be messy!).  Then just <mark> tags with different bgcolor style tags would work, that's what I have coming out of my Solr highlighting anyway.  

In the PDFs themselves though I can implement multiple colors too, like I switched from yellow to cyan but now different terms can have different colors.  My REST controller would have to be a bit more complicated to specify it generically but I could do that.  But it's too separate issues, highlighting text/HTML views and highlighting PDF files, I have to use PDFBox to write that code while in HTML it's simpler.

So we'd have to split this into two separate issues:

- [ ] Highlighting within the HTML view with different colors (simpler)
- [ ] Highlighting within the PDF by modifying the REST controller to give keywords and colors (right now it already supports as many keywords as you like but just one color)

**Comment by lukeczapla** [comment]
Closing this one since we have highlighted the PDFs
