### ISSUE TITLE
Article Screening Scoring System

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#2908]
## Current
Gene/Alteration scoring based on:
A In the full-text, for each mention of the alteration:		+2
B Mention of the gene name (or synonym) in title or keywords:	+4
C Mention of the gene name (or synonym) in the abstract:		+2
D No mention of the gene name in title/keyword/mesh/abstract:  	-4
G No mention of the alteration in title/keyword/mesh/abstract:	-4
E Mention of the alteration (or synonym) in the title or keywords:	+8
F Mention of the alteration (or synonym) in the abstract:		+4
H Supporting Texts: for each mention of the alteration		+2
I For each supporting text mentioning the alteration		+2

Second scoring based on # of functional keywords

## Proposed

1.  As long the article has gene mentioned >5 times, the article gets base score 10. (Technically these articles should not even be associated with the query)
2. Alteration point. Point based on Section * Multiplier (Only use the highest point calculated based on the section. So the highest score here would be 9 points):
Section:
Title or Abstract: 3
Main Text: 2 
Supporting Text (including the supplemental file, table and figure): 1
Multiplier:
Keyword mentions [2-5] times: 1
Keyword mentions [6-10] times: 2
Keyword mentions >10 times: 3
3. Functional keywords mentioning
[1-5] functional keywords, add 5 points
`>=6` functional keywords, add 10 points

**Comment by zhx828** [comment]
One issue with the new scoring I can think of is the closeness of the scoring. A lot of articles may end up with same score.
We should use this aggregated score to sort matches, but we should show the details of scoring. For instance,
`Functional keyword relevance: High/Medium/Low`
`Alteration relevance: High/Medium/Low`

**Comment by lukeczapla** [comment]
this is a great idea, so we want to be able to tune it, yes this fits fairly easily in now and that one has new rules but goes with counting each category - so we can refactor this and assign some numbers to those categories (maybe just one knob  High/Medium/Low because it could be how much functional is, the rest is alteration) , and perhaps then it will be more tuneable and that's where feedback comes in and the display of the setting would help.  We could curate at all different settings too (1,2, and 3?), more data but I think it will work as an option!.

**Comment by lukeczapla** [comment]
So I am looking here at this and [1-5] functional keywords adds 5 points (for each one, or just 5 points?) and >=6 adds 10 points.  So this is either going to be worth very little if its as a whole, or now we'll have f scores going into a total that are in the 1000's, since there were ones with f=195 assigning just 1 point per mention.  And also now, the two scores all go into one total with some output about whether each article scored high or low (or medium) on each, so for this all we can do is collect the statistics.

So I'm working on the alteration points right now because it'll give us something quick to browse for each article's statistics, but adding them together, do you think that works here?  Because if it was 5 or 10 points depending on the number of functional keywords, that contribution will still overshadow the alteration scores...

**Comment by lukeczapla** [comment]
Okay, I have calculated this, now we will take the statistics for each.  In order to make it 0-10, I added one point to alteration score if there was more than 1 mention (to put it into category [2-5] or greater)

**Comment by lukeczapla** [comment]
81534 articles scored
Alteration Score Histogram
0 2958
1 0
2 19548
3 24886
4 6201
5 6699
6 1769
7 16583
8 1921
9 662
10 307


Functional Score Histogram
0 32025
1 0
2 0
3 0
4 0
5 14695
6 0
7 0
8 0
9 0
10 34814


Total Score Histogram
0 462
1 0
2 3326
3 5246
4 1364
5 1858
6 359
7 5124
8 2923
9 887
10 1323
11 232
12 6473
13 5140
14 1608
15 1045
16 612
17 2025
18 298
19 181
20 380
21 0
22 2536
23 4609
24 1150
25 1731
26 220
27 6607
28 2890
29 842
30 1297
31 100
32 5766
33 5438
34 773
35 1832
36 246
37 4274
38 263
39 58
40 36

**Comment by lukeczapla** [comment]
So I managed to clean this up and assign the points in the obvious part where it drops the article if nothing's mentioned at all -> they all had to pass that check!  Right now though I think we have the opportunity to get the paragraphs totally correct and move out the table information into records, I've been building an engine on top of PDFBox specifically for us, so let's see what we can do with the new scores and also just refactoring the frontend entirely soon, I really think we need to use the full PDF functionality and compare against the Tika output for reasonable validation (i.e., some texts were so old they are just photocopies on a scanner, and there the OCR has to read them entirely and it's easy to compare lengths and such to see what was actually fished out).  

So I will run recuration over hongxin1 and AKTtest for these scores right now, but AAVariants takes so long I only redid ERBB2 for Moriah and I'm working on getting rid of all the "junk"/"spam" that Tika kinda put at ends of pages and stuff (headers/footers, that was the easiest) and perfecting the tables (these tab "\t" guys actually work pretty well and I've had to discover new things like getWidthOfSpace from PDFBox and it seems 90 degree page rotations are usually just pages that are entirely tables where there's perhaps a legend).

The whole PDF thing is now a separate package so it'll be super reusable as well, some stackoverflow material helped me out a ton, too.  Even without the cleanup, SentenceDetectorME does a great job with the "Sentence Island" thingie in the frontend, but Paragraph was just junk so now I believe we can make the right connections in the PDF and write it out better, after doing it the silly way and getting really far, I went ahead and made an object-oriented system to do it easily and annotate it up and serialize it so it could even be committed to the MongoDB to go back to the analysis

**Comment by lukeczapla** [comment]
So checking everything with the original meaning (we'd changed the +10 to +20 for gene > 5 mentions just because you'd said less than that would mean it shouldn't really be on the list at all, so they get put at the end) and redoing it, here's the new histogram for ALL the keys together

Alteration Score Histogram
0 0
1 2288
2 38283
3 13327
4 4337
5 0
6 11172
7 0
8 0
9 13523
10 0


Functional Score Histogram
0 32647
1 0
2 0
3 0
4 0
5 14938
6 0
7 0
8 0
9 0
10 35345


Total Score Histogram
0 0
1 312
2 6660
3 3359
4 976
5 0
6 2755
7 3943
8 1540
9 2497
10 0
11 1527
12 9881
13 2477
14 1405
15 0
16 2155
17 0
18 0
19 1437
20 0
21 233
22 5716
23 2726
24 843
25 0
26 2699
27 2989
28 1676
29 4996
30 0
31 1456
32 9094
33 1549
34 2413
35 0
36 2323
37 0
38 0
39 3293
40 0


So my final comments would just be this:

1) Maybe if alteration score >= 4, we should add +1?  Because it looks nicer out of 10 for alteration and then 0-3 can be low, 5-7 can be medium (6 wouldn't exist actually), and 10 could be high (since 8 and 9 won't exist).
2) I think maybe the functional score criteria was too low and 1 match isn't much at all, so perhaps f score (original old version counting numbers) of 2-10 should be 5 points, and >10 should be 10 points?  Because as it is right now, we have some with f = 100 with the old scoring system, so it'd help get those to the top.
3) For ties, we could use the old score as the tie breaker?  Because I see a Top 10 PMIDs for one of our variant records with a lot of results all with total score = 39 and then it's impossible to tell which ones should really be top 5.
