### ISSUE TITLE
Issues with the parsed full text

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3008]
- [x] check why `To` is included in the first paragraph of PMID19376813
- [x] parse the references to a list and return through API

**Comment by lukeczapla** [comment]
All finished, closing this and putting more improvements into #3009 before that one is closed because this has been a task that's taken awhile so there is still more to do now that the problem has been "cracked" (i.e., the parser runs through several PMIDs and works, but still may require additional work and new features)
