### ISSUE TITLE
Return the parsed full text through api with sections

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3009]
Return the text in json that with section information: section name, whether it's subtitle.

**Comment by lukeczapla** [comment]
So we have created the endpoint but now in terms of what can be done further here is some more items:

- [ ] Tables are encoded as text (it's NOT feasible to just capture a corner of the PDF because my code doesn't actually render anything, which helps it to parse the whole thing in only 1-2 seconds), but to annotate them with the correct number of tabs, the presence of subscripts/superscripts, and anything else, it will be possible to create an endpoint with an example of how an HTML table is made (with table, td, tr tags and the sub or super tags for the text), which can then be used directly, or the method code put into TypeScript/JavaScript to do it in the frontend.
- [ ] Identifying the superscripts/subscripts in the main text, so that in the future they could be removed, and superscripts for citations could be linked to the right article in citations.
- [ ] Variables/macros for Figures & Tables in HTML view like proposed ${Figure 1} variable
- [ ] General testing of many more PDFs

So this would be the mo

**Comment by lukeczapla** [comment]
Endpoint for text representation: https://aimlcoe.mskcc.org/knowledge/textArticle/{pmid}
Endpoint for demo HTML representation (including the tables as tags table, td, tr): https://aimlcoe.mskcc.org/knowledge/HTMLArticle/{pmid}

To do: Implement ${Figure 1} to Hongxin's specifications, debug more PMIDs
