### ISSUE TITLE
Look into Airflow authentication to allow user registration

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3357]
- [x] User registration
- [x] Expose service as airflow.oncokb.org
- [x] Setup in production cluster

**Comment by calvinlu3** [comment]
Airflow has configuration to enable user self registration via the login page. ([ref](https://airflow.apache.org/docs/apache-airflow/stable/security/webserver.html#other-methods)). 
To configure through bitnami/airflow helm chart, we need to pass in a configmap containing the [webserver_config.py](https://github.com/apache/airflow/blob/main/airflow/config_templates/default_webserver_config.py) file as a string via the `web.existingConfigmap` value ([ref](https://github.com/bitnami/charts/blob/main/bitnami/airflow/templates/web/deployment.yaml#L248))

Since only the devs will be using Airflow, we don't need user self registration. We will stick to the admin creating user accounts via the Airflow web ui (https://airflow.oncokb.org/users/add)
