### ISSUE TITLE
Allow search cancer type in the home page search box

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3415]
Current in the home page https://www.oncokb.org/, we allow user to search Gene/Alteration/Drug. It would also helpful if user   types in cancer type and we provide some info.
The matched option could include
- [ ] `The cancer type has Level 1 in {gene} {alteration}`
- [ ] Once click on it, it takes user to gene page, similar when you search a drug(for instance, Vemurafenib)

**Comment by Spnetic-5** [comment]
Hello @zhx828,
I'm interested in participating in the Google Summer of Code (GSoC) 2023 program and contributing to the **Annotate cancer alterations and generate patient report** project under your mentorship.

-  I have followed the instuctions you mentioned in order to proceed with the project in this [comment](https://github.com/cBioPortal/GSoC/issues/95#issuecomment-1456772482)

I'm interested in solving this issue, could you please assign this issue to me?

**Comment by Spnetic-5** [comment]
CC: @calvinlu3 @zhx828

**Comment by zhx828** [comment]
@Spnetic-5 this ticket would require some knowledge on both java and javascript. It also requires knowledge on both [oncokb](https://github.com/oncokb/oncokb) and [oncokb-public](https://github.com/oncokb/oncokb-public) repos. I would suggest working on some other issues before working on this one.

**Comment by zhx828** [comment]
Few issues need to addressed:
- Use `:` after level, instead of `in`
- Show `(A1, A2, A3 and other ** alterations)` instead of `and more`
- Use alteration.name instead of alteration.alteration
- Verify why BRAF does not show up for melanoma in Level 1
- Show genes that are more relevant to the cancer type(Hongxin)
