### ISSUE TITLE
Create tests to cover FirebaseCRUD store

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb#3538]
We want to validate the CRUD actions are properly reflected in the firebase.

- [x] Create unit tests
- [x] Jest to mock Firebase store
- [ ] ~~Screenshot tests using puppeteer~~
   - [ ] ~~Screenshot test would require the app to built and started, but there are dependencies like Keycloak. What is a workaround?~~

**Comment by calvinlu3** [comment]
There are a couple ways to test the **Firebase store**. 

**✔️ Method 1 : Firebase Test SDK in Online Mode**
 - Interacts with a real firebase project that is created for testing
 - Since it interacts with real data, we need to take care of seeding and cleaning up data. 
 - Runs slower than in offline mode

**Method 2: Firebase Test SDK in Offline Mode**
- We don't need to create a new Firebase project, so minimal configuration
- Increases complexity of test code because we need to write our own firebase function stubs.

** Method 3: Local Firebase Emulator**
- We can use a local firebase that emulates the behavior of a real firebase db.
- Adds additional complexity to the setup/configuration
- Similar to the online mode test SDK, it mimics the behavior of real firebase.

**Comment by calvinlu3** [comment]
We will leave out screenshot testing from this ticket and will resolve in this follow-up [ticket](https://github.com/oncokb/oncokb/issues/3568)
